stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

build:
  stage: build
  script:
#    - bundle install
#    - bundle exec fastlane build
#    - ls
    - pwd
