stages:
  - build

#before_script:
#  - echo Hello World
#  - cd ios

variables:
#  LC_ALL: "en_US.UTF-8"
#  LANG: "en_US.UTF-8"
#  GIT_STRATEGY: clone
  IOS_FOLDER: ios

build:
  stage: build
  script:
    - ls
    - pwd
    - BUNDLE_GEMFILE="ios/Gemfile" bundle install
    - echo $IOS_FOLDER    
#    - cd $IOS_FOLDER    
#    - fastlane gym --workspace "ios/medicoconsultor.xcworkspace" --scheme "medicoconsultor" --clean
#    - bundle exec fastlane build

