stages:
  - build

before_script:
  - echo Hello World
  - cd ios

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

build:
  stage: build
  script:
    - ls
    - pwd
#    - bundle install
    - BUNDLE_GEMFILE="ios/Gemfile" bundle install
#    - cd ./ios
#    - bundle exec fastlane build

