stages:
  - build

#before_script:
#  - echo Hello World
#  - cd ios

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

build:
  stage: build
  script:
    - ls
    - pwd
    - BUNDLE_GEMFILE="ios/Gemfile" bundle install
    - fastlane gym --workspace "ios/medicoconsultor.xcworkspace" --scheme "medicoconsultor" --clean
#    - bundle exec fastlane build

