# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Archive IPA"
  lane :beta do
#    increment_build_number(xcodeproj: "ios/medicoconsultor.xcodeproj")
#    build_app(workspace: "ios/medicoconsultor.xcworkspace", scheme: "medicoconsultor")
    increment_build_number(xcodeproj: "medicoconsultor.xcodeproj")
    build_app(workspace: "medicoconsultor.xcworkspace", scheme: "medicoconsultor")
    
    gym    
#    gym --export_method enterprise
  end
end

